name: 
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - rdkit==2021.03.1
  - pip>=21.0
  - pip:
    - https://download.pytorch.org/whl/cpu/torch-1.10.0%2Bcpu-cp38-cp38-linux_x86_64.whl
    - furo
    - numpy
    - sphinx
    - sphinx_rtd_theme==0.5.2
    - torch-scatter==2.0.9
    - torch-sparse==0.6.13
    - torch-cluster==1.6.0
    - torch-spline-conv==1.2.1
    - torch-geometric==2.0.0
    - git+https://github.com/Chilipp/autodocsumm.git
    - captum==0.2.0
    - cilog
    - typed-argument-parser==1.5.4 
    - tensorboard
    - sympy
